In [15]:
import tensorflow_hub as hub
import tensorflow_text as text


In [16]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [17]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [18]:
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [19]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [20]:
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [21]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [23]:
bert_model = hub.KerasLayer(encoder_url)

In [24]:
bert_results = bert_model(text_preprocessed)

In [25]:
bert_results.keys()

dict_keys(['sequence_output', 'default', 'pooled_output', 'encoder_outputs'])

In [26]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292037,  0.08567796,  0.14476822, ..., -0.09677086,
          0.08722138,  0.07711112],
        [ 0.17839383, -0.19006042,  0.50349367, ..., -0.05869792,
          0.32717133, -0.15578459],
        [ 0.18701458, -0.43388757, -0.48875144, ..., -0.15502812,
          0.00145101, -0.24470942],
        ...,
        [ 0.12083109,  0.12884255,  0.46453556, ...,  0.07375517,
          0.1744196 ,  0.16522068],
        [ 0.0796788 , -0.01190656,  0.5022541 , ...,  0.13777743,
          0.21002224,  0.00624595],
        [-0.07212707, -0.2830347 ,  0.59033394, ...,  0.47551903,
          0.1666849 , -0.08920363]],

       [[-0.07900621,  0.3633513 , -0.2110154 , ..., -0.17183754,
          0.16299736,  0.6724268 ],
        [ 0.2788348 ,  0.43716303, -0.35764742, ..., -0.04463677,
          0.38315165,  0.588798  ],
        [ 1.2037672 ,  1.0727024 ,  0.48408818, ...,  0.24921016,
          0.4073087 ,  0.4048183 ],
        ...,

In [27]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.791774  , -0.21411917,  0.4976954 , ...,  0.24465214,
        -0.47334468,  0.8175868 ],
       [-0.9171231 , -0.47935167, -0.7865698 , ..., -0.6175175 ,
        -0.7102687 ,  0.9218429 ]], dtype=float32)>

In [28]:
len(bert_results['encoder_outputs'])

12

In [29]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

In [30]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901434,  0.00644743, -0.03614967, ...,  0.04999617,
           0.06149198, -0.02657539],
         [ 1.1753384 ,  1.2140787 ,  1.1569979 , ...,  0.11634348,
          -0.3585536 , -0.40490168],
         [ 0.03859051,  0.5386999 , -0.21089795, ...,  0.21858181,
           0.7260164 , -1.1158605 ],
         ...,
         [-0.07587031, -0.25421906,  0.7075512 , ...,  0.50541973,
          -0.18878675,  0.15028358],
         [-0.16066602, -0.2808966 ,  0.57597053, ...,  0.52758545,
          -0.11141393,  0.02887567],
         [-0.04428172, -0.20279574,  0.5909355 , ...,  0.8133834 ,
          -0.39075816, -0.02601738]],
 
        [[ 0.18903589,  0.0275255 , -0.06513737, ..., -0.00620204,
           0.15053886,  0.03165446],
         [ 0.59161496,  0.7589141 , -0.07240654, ...,  0.6190398 ,
           0.8292889 ,  0.16161954],
         [ 1.446083  ,  0.44602647,  0.40990257, ...,  0.48255908,
           0.6269115 ,  0.13